import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

//this will render on client side

export default function Home({results}) {
    // destructuring the result
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.logo.wine/a/logo/Hulu/Hulu-Logo.wine.svg" />
      </Head>

     <Header />

     <Nav />

        {/* pass the result as props on result components */}
        {/* it takes array as props and render on frontend */}
     <Results results={results}/>

    </div>
  )
}
// this will render on server side
// server rendering happens first then it gets delivered to the clients
// server side rendering props with help of async function
// here context include important details of what does the url are user given 

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
